const mongoose = require('mongoose');

const questionSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      required: true, // Question type is mandatory
      enum: ['categorize', 'multiple-choice', 'text', 'image'], // Example of allowed types
    },
    question: {
      type: String,
      required: true, // The question text is mandatory
    },
    options: {
      type: mongoose.Schema.Types.Mixed,
      default: {}, // Default to an empty object/array
    },
    image: {
      type: String,
      default: null, // Optional question image
    },
  },
  { _id: true } // Use MongoDB's default autogenerated IDs for each question
);

const formSchema = new mongoose.Schema(
  {
    formTitle: {
      type: String,
      required: true,
      default: 'Untitled Form',
      index: true, // Indexed for faster searches
    },
    headerImage: {
      type: String,
      default: null, // Explicitly setting default as null
    },
    questions: [questionSchema], // Embedded schema for questions
  },
  {
    timestamps: true, // Automatically adds createdAt and updatedAt
  }
);

module.exports = mongoose.model('Form', formSchema);
